version: 0.2

phases:
  install:
    commands:
      - export PATH=$PATH:$(pwd)/vendor/tools/codebuild
      - export PATH=$PATH:$(pwd)/bin
      - export DOCKER_BUILDKIT=1
      - docker-login
  pre_build:
    commands:
      - |
        #
        # Build test.
        #
        set -eu;
        build-test;
  build:
    commands:
      - |
        #
        # Push to ECR.
        #
        set -eu;
        if trigger is release ?; then
          push-to-ecr ./Dockerfile execution-environment-tester;
          push-to-docker-hub ./Dockerfile execution-environment-tester;
        fi;
  post_build:
    commands:
      - |
        #
        # Notify the result.
        #
        set -eu;
        notify-release-image execution-environment-tester;
        notify-build-result execution-environment-tester;
